spring.application.name=proxy
server.port=8081


spring.data.redis.host=192.168.194.250
spring.data.redis.port=6379
# spring.data.redis.password=


spring.kafka.bootstrap-servers=192.168.194.250:9092
spring.kafka.consumer.group-id=grupo_alumno_artola
spring.kafka.consumer.auto-offset-reset=earliest


catedra.api.url=http://192.168.194.250:8080
catedra.api.token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ2YWxlbnRpbmFfdjQiLCJleHAiOjE4NTIzNzIzNzUsImF1dGgiOiJST0xFX1VTRVIiLCJpYXQiOjE3NjU5NzIzNzV9.yz4wP2Zx8JFwrjKfE8xLCDs_J1GPfpGob-I_d3hMKf9ZZ7mNqbGPpSfm7zAw5GVHJt7CtdixCkPp546S520D-g
catedra.id=valentina_v4


backend.service.url=http://localhost:8080
internal.api.secret=SecretoValentina123