spring.application.name=backend

# =======================================================
# CONFIGURACION JWT
# =======================================================
jwt.secret = YXV0b2dlbmVyYWRhcG9ycHJveWVjdG9hdXNlbmNpYTk4NzY1NDMyMTA=
jwt.expiration = 604800000

